### ISSUE TITLE
Ejemplo de script de provincias con ID

### ISSUE THREAD

**Issue by barbanet** [TodoPago/Plugin-Magento#1]
El script que figura en el [README.md](https://github.com/TodoPago/Plugin-Magento#sp) incluye ids. ¿Podría arreglarse para que no los incluya ya que generaría conflictos en algunas instalaciones?

**Comment by damianwajser** [comment]
Damian, 

Tal como dice el readme es un script tentativo para ser modificado dependiendo la implentacion custom que tenga la tienda, estamos trabajando para modificarlo a una implementacion univiersal.

Gracias por el comentario.
Slds!
