### ISSUE TITLE
CRITICO - El módulo rompe el funcionamiento de agrements de Magento

### ISSUE THREAD

**Issue by barbazul** [TodoPago/Plugin-Magento#12]
A menos que se me esté escapando algo, el rewrite que hace el módulo sobre el bloque de checkout agreements es exclusivamente para reemplazar el template original de Magento por un template vacío.

Independientemente de lo incorrecto de esa solución para reemplazar un template, esto efectivamente rompe la funcionalidad de "Aceptar términos y condiciones" nativa de Magento, potencialmente causando que no se pueda completar el checkout en un sitio que tuviera esa función habilitada al momento de instalar el módulo .

El PR#11 propone una solución incorrecta, reemplazando el contenido del template por el default de Magento.

Este commit, generado en base al descubrimiento de augustojbusso remueve por completo el rewrite sobre el bloque: https://github.com/barbazul/Plugin-Magento/commit/53f1992bcc579da7b4c9c69081648a36440aa247

**Comment by damianwajser** [comment]
solucionado en version 1.4.2
