### ISSUE TITLE
CRITICO - Definicion incorrecta del metodo getModo

### ISSUE THREAD

**Issue by barbazul** [TodoPago/Plugin-Magento#13]
El metodo getModo del helper Connector espera un parámetro $modo pero el llamado de getHeader del mismo helper no pasa dicho parámetro, causando que no se pueda completar el checkout 

https://github.com/barbazul/Plugin-Magento/commit/33049f42cb16677d3cf8af14c0ecb5120ebf168b

**Comment by damianwajser** [comment]
solucionado en version 1.4.2
