### ISSUE TITLE
Consulta de transacciones sin datos

### ISSUE THREAD

**Issue by desarrollo-rollpix** [TodoPago/Plugin-Magento#17]
Al intentar ver información desde el tab del pedido se muestra la leyenda "sin datos" y cuando realizo la llamada manual me devuelve lo siguiente

https://apis.todopago.com.ar/t/1.1/api/Operations/GetByOperationId/MERCHANT/[MerchantID]/OPERATIONID/[OperationID]

<OperationsColections xmlns="http://api.todopago.com.ar"><Status>702</Status></OperationsColections>

Cuál es el problema?

gracias

**Comment by desarrollo-rollpix** [comment]
Por lo que veo es un problema del MerchantID en la llamada manual al menos.

array (size=2)
  'StatusCode' => int 702
  'StatusMessage' => string 'ERROR: Cuenta Inexistente' (length=25)
(length=30)

**Comment by drarko** [comment]
Estimado,

¿La transacción aparece en el portal de TodoPago?

¿La llamada manual la estas realizando por SDK? Por favor, recorda setear
correctamente el API Key en el header Authorization.

Saludos

**Comment by desarrollo-rollpix** [comment]
Hola!
Para ser más claro adjunto unas capturas. Lo que sucede es que en el Tab "Información de Pago" no veo ningún dato respecto a la transacción, a pesar de que el pago está Aprobado. Respecto a la llamada manual, fue un intento de detectar lo que sucedió.

![100000349_1](https://cloud.githubusercontent.com/assets/12416775/18672243/b9e5bd14-7f1d-11e6-81b6-bab072aeca97.png)
![100000349_2](https://cloud.githubusercontent.com/assets/12416775/18672244/b9ebff9e-7f1d-11e6-9028-380ea8cb4479.png)

Hay algo a nivel configuración que me esté faltando??

**Comment by drarko** [comment]
Estimado,

Para analizar el incoveniente, necesitaríamos el log de Magento (system.log) donde el plugin registra los datos correspondientes para ver si es un problema de configuración o un bug. ¿Podrian enviarlo?

Gracias

**Comment by desarrollo-rollpix** [comment]
@drarko te pido disculpas. La versión que teníamos era la 1.2.1 y al actualizarla a la 1.5.1 se solucionó este problema.

Gracias

**Comment by drarko** [comment]
Perfecto entonces

Muchas gracias

**Comment by drarko** [comment]
Hola TodoPago/Plugin-Magento,
Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 
Haz click aqui a.iqelite.com/j/0NJf2L/fbg/?hg=RgbuGvkP7l para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=8089488d&email=reply@reply.github.com.&hg=RgbuGvkP7l IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
