### ISSUE TITLE
No carga la configuracion.

### ISSUE THREAD

**Issue by mvaisberg** [TodoPago/Plugin-Magento#20]
Copio y pego todas las carpetas del modulo en la instalacion de magento y no carga la configuracion del modulo en payment methods.

**Comment by mroffe** [comment]
@mvaisberg los pasos basicos serian: reindexar, limpiar cache, verificar el que xml este en true y sobre todo, verificar que la versión de PHP sea 5.4 o superior. Anterior a eso, el modulo rompe varias partes del backend :(

**Comment by mvaisberg** [comment]
@mroffe Acabo de probar localmente con 2 proyectos, borrando cache, reindexando, teniendo php superior a 5.4 y con el xml del modulo de todo pago en true (como viene por defecto) y no me carga la configuracion. Si por ejemplo corre los sql de instalacion porque aparecen en la tabla core_resource pero no puedo hacer que aparezca la configuracion del system.xml :S

**Comment by drarko** [comment]
@mvaisberg ¿podrías enviarnos los logs de errores del servidor y de Magento para analizar el inconveniente? Gracias

**Comment by mvaisberg** [comment]
@drarko No tira errores en el log, solo no me carga el modulo para configurarlo aca:

![selection_002](https://cloud.githubusercontent.com/assets/4543889/19698501/d01b531c-9aef-11e6-826c-d5bb845e8c8d.png)

Pero por ejemplo si corrio los sql:

![selection_004](https://cloud.githubusercontent.com/assets/4543889/19698535/f93c1a7e-9aef-11e6-88f2-733852ee0519.png)

Ustedes si ahora agarran un magento pelado, y tiran el modulo les aparece la configuracion?

**Comment by drarko** [comment]
@mvaisberg Si, probando en una instalacion limpia, el modulo aparece luego de refrescar el cache de Configuration. ¿Que version de PHP y de Magento estas utilizando?

**Comment by mvaisberg** [comment]
@drarko acabo de instalar una vesion limpia de magento (1.9.3.0), puse la extension de todo pago y sigue sin funcionar la parte de la configuración (borre cache, reindex, etc).

Version de PHP:
![selection_005](https://cloud.githubusercontent.com/assets/4543889/19701399/87b0eaf4-9afb-11e6-8a59-5a02665ce9ae.png)

**Comment by drarko** [comment]
@mvaisberg 
Instalamos un magento 1.9.3.0 limpio.

Y luego de refrescar el siguiente cache:
![snapshot1](https://cloud.githubusercontent.com/assets/7052804/19702454/217c8c36-9ad6-11e6-9a13-fb77801bc602.png)

El modulo se muestra sin problemas
![snapshot2](https://cloud.githubusercontent.com/assets/7052804/19702493/4c8358ec-9ad6-11e6-9d03-9ec0adc302e3.png)

Necesitariamos mas informacion para poder determinar si existe un problema con el plugin y tu ambiente, como logs de apache, php, magento, etc.

**Comment by mvaisberg** [comment]
@drarko lo instale en otro entorno y parece funcionar, debe ser un error de mi entorno , intento ver que configuracion tengo mal para que no corra y les aviso.

Gracias
