### ISSUE TITLE
Error: Estado del Pedido

### ISSUE THREAD

**Issue by JonaPolo** [TodoPago/Plugin-Magento#22]
Estimados, buen día, estoy teniendo un problema cuando realizo un pago, esto cuando termino de efectuar el pago y regresa a la pagina del carrito de compras y el resultado es "se produjo un error. se cancelo el pago". Lo raro es que el pago si se efectua, pero en el magento directamente el estado cambia a Cancelado, con este error:

Todo Pago (Exception): exception 'Mage_Core_Exception' with message 'El estado del pedido "complete" no se debe establecer manualmente.' in /home/..../app/Mage.php:595 Stack trace: #0 
/home/...../app/code/core/Mage/Sales/Model/Order.php(1013): Mage::throwException('El estado del p...') #1 /home/..../app/code/core/Mage/Sales/Model/Order.php(990): Mage_Sales_Model_Order->_setState('complete', 'complete', 'Todo Pago: APRO...', NULL, true) #2 /home/..../app/code/community/Todopago/Modulodepago2/controllers/PaymentController.php(272): Mage_Sales_Model_Order->setState('complete', 'complete', 'Todo Pago: APRO...') #3 /home/..../public_html/ventas/app/code/community/Todopago/Modulodepago2/controllers/PaymentController.php(196): Todopago_Modulodepago2_PaymentController->lastStep('500000223', 'c664ebea-132f-d...') #4 /home/.../public_html/ventas/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Todopago_Modulodepago2_PaymentController->secondStepAction() #5 /home/..../public_html/ventas/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('secondStep') #6 /home/..../public_html/ventas/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #7 /home/..../public_html/ventas/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch() #8 /home/.../public_html/ventas/app/Mage.php(684): Mage_Core_Model_App->run(Array) #9 /home/.../public_html/ventas/index.php(83): Mage::run('', 'store') #10 {main}

Como les decia, el pago si se efectua, pero en el magento siempre lo cancela. Necesito solucionar esto, porfavor, alguna ayuda. Graciassss

**Comment by drarko** [comment]
Estimado,

Este error es propio del comportamiento de Magento. Ya que no se permite que una orden pase directamente a estado Complete sin pasar por Processing. Y ese es el error que esta sucediendo, tal cual lo indica el mensaje.

Desde el plugin no podemos cambiar este comportamiento estándar de Magento.

Puede solucionarlo cambiando el estado para en el cual queda la orden luego de aprobado el pago.

Saludos

**Comment by JonaPolo** [comment]
Mauricio, gracias por su pronta respuesta. Realizare el cambio que me
indicaste.

Saludos,

Jonathan Polo


2016-11-07 18:12 GMT-03:00 Mauricio <notifications@github.com>:

**Comment by JonaPolo** [comment]
Buen día, solo para confirmarles que realice los cambios y efectivamente
era ese el problema. Muchas gracias, solucionado.

Jonathan Polo



2016-11-07 18:36 GMT-03:00 Jonathan Polo Velezmoro <tecjpolo@gmail.com>:
