### ISSUE TITLE
Prevencion de fraude

### ISSUE THREAD

**Issue by molanovsky** [TodoPago/Plugin-Magento#27]
¿Como funcionan los nuevos atributos de "Prevencion de fraude"?
O sea, ¿un retail que hace envíos por transporte privado que debería seleccionar?
Porque la documentación no especifica nada y las opciones no son para nada claras.

**Comment by drarko** [comment]
Estimado, 
Debe seleccionar el segmento Retail al momento de configurar el plugin. Los campos actualmente se estan tomando de la direccion de facturacion y envio del comprador.
