### ISSUE TITLE
V 1.8 : Notice en Payment Controller, linea 45

### ISSUE THREAD

**Issue by joaquin-becerra** [TodoPago/Plugin-Magento#29]
Al redireccionar al form de pago luego de completar una orden

Notice: Undefined variable: message  in app/code/community/Todopago/Modulodepago2/controllers/PaymentController.php on line 45

**Comment by barbazul** [comment]
@joaquin-becerra Acá tenés un fix.... https://github.com/barbazul/Plugin-Magento/blob/master/app/code/community/Todopago/Modulodepago2/controllers/PaymentController.php#L43

**Comment by barbazul** [comment]
Revisando el commit, es un bug viejo. De Noviembre.

**Comment by drarko** [comment]
Solucionado en las ulitmas versiones. Reabrir en caso de ser necesario.
Gracias
