### ISSUE TITLE
Carga de categorías de producto errónea e innecesaria

### ISSUE THREAD

**Issue by barbazul** [TodoPago/Plugin-Magento#3]
En https://github.com/TodoPago/Plugin-Magento/blob/master/app/code/community/Todopago/Modulodepago2/Model/Cybersource/Cybersource.php#L102

**Comment by barbazul** [comment]
Se ve que se borró mi comentario anterior, pero hay varias cosas ahí:

1. Se hace un load sobre cada producto dentro de un foreach, lo cual tiene un impacto negativo en performance
2. Se asume que el producto tiene al menos una categoría y lanza un error cuando $cats[0] no está definido
3. Se hace un load sobre la primera categoria de cada producto y no se controla si la misma ya fue cargada en una iteración anterior
4. Se vuelve a cargar el producto para obtener un atributo distinto.

Solamente este algoritmo alcanza para volver al módulo inviable de incorporación a a cualquier proyecto Magento serio.

**Comment by damianwajser** [comment]
Buenos días. ..
Podrías darnos más detalle de por qué crees innecesaria la.carga de categorias en esa línea?

**Comment by barbazul** [comment]
Es un error de performance. 

No lo digo yo, lo dice Magento: https://info2.magento.com/rs/318-XBX-392/images/optimize-your-site-performance.pdf (pagina 9)

Les recomiendo hacer una validación del modulo usando herramientas como Judge o el standard Ecg para PHP Code-Sniffer, que les va a reportar inmediatamente esos mismos issues.
