### ISSUE TITLE
Cuotas con interes

### ISSUE THREAD

**Issue by mvaisberg** [TodoPago/Plugin-Magento#32]
Hola,

La api permite que el interes de las cuotas lo pague el cliente? o poder mandar intereses a las cuotas?

Desde el modulo de magento vi que no se puede hacer pero porai puedo modificar el codigo como para poder hacer que las cuotas tengan interes cuando se redirecciona a todo pago

Desde ya gracias,

Saludos

**Comment by drarko** [comment]
@mvaisberg por favor, para este tipo de consultas no tecnicas, comunicate con el callcenter o a traves del formulario de contacto del Portal.
Gracias

**Comment by mvaisberg** [comment]
Es una pregunta tecnica. Estoy consulta si la API permite agregarle interes a las cuotas
