### ISSUE TITLE
ERROR: El campo CSITPRODUCTDESCRIPTION es incorrecto

### ISSUE THREAD

**Issue by jpmayoral** [TodoPago/Plugin-Magento#4]
Al concatenar los campos de la descripcion de los productos, si exceden los 255 caracteres el gateway devuelve que es incorrecto.

No habria que concatenarlos para que no pasen estas cosas. Lo mismo pasa con los nombres de los productos.

Saludos!

**Comment by damianwajser** [comment]
Esta en desarrollo esa modificacion. Slds!

**Comment by jpmayoral** [comment]
Muchas gracias por contestar Damián! Saludos!
