### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by waltercaballero** [TodoPago/Plugin-Magento#6]
Obtengo un error 500 una vez que doy click en "Finalizar Compra" habiendo seleccionado "Todopago" como metodo de pago.

El error 500 lo obtengo cuando el sistema intenta acceder a: http://[tienda_magento1.8_base_url]/modulodepago2/payment/getPayData/

Información Adicional:

El modulo lo activo desde: Setting->Configuration->Payment Method 
pero para que no me de error, tengo que desactivar el modulo "Todopago_Modulodepago2" en:
Sistema -> Avanzado -> Avanzado 

Cuando dejo ambos activados, recibo el error:  "The requested Payment Method is not available."  al querer proceder con la compra, al inicio del checkout. Adjunto report file.
[1190374194543.txt](https://github.com/TodoPago/Plugin-Magento/files/156702/1190374194543.txt)

Estoy usando la versión del plugin 1.2 y Magento 1.8.1, tengo todas las extension php necesarias, habilitadas.

**Comment by damianwajser** [comment]
Consulta, cuando decis "dejo ambos activados" a que 2 te estas refiriendo? al modulo TP y cual otro?
Gracias!

**Comment by wcaballero** [comment]
Me refiero a los 2 lugares donde tengo que configurar la activacion:

1- Como indica la documentación de la extension, activar el metodo de pago: 
Setting->Configuration->Payment Method

2- Desactivar el modulo "Todopago_Modulodepago2" en los modulos del magento:
Sistema -> Avanzado -> Avanzado

si te queda cómodo alguna otra manera de contacto, no tengo problemas de coordinar.

**Comment by damianwajser** [comment]
Excelente, en breve te estaré contactando por hangout para compartir pantalla y ver este issue en vivo.
Y luego publicaremos la solución por este medio.
Gracias!

**Comment by wcaballero** [comment]
Perfecto, quedamos asi.

Muchas gracias !

**Comment by damianwajser** [comment]
Te estoy hablando por ese medio, estas conectado?
Gracias!

2016-03-03 9:43 GMT-03:00 Walter Caballero <notifications@github.com>:

> Perfecto, quedamos asi.
>
> Muchas gracias !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TodoPago/Plugin-Magento/issues/6#issuecomment-191748536>
> .
>



-- 
Damian Wajser
Developer Java Sr. / Tech Leader
Sofftek Argentina.
Cel: 15-6-235-6268

**Comment by waltercaballero** [comment]
Bien, trabajando en conjunto con ustedes, doy fe de que ambos errores han sido corregidos.

Quedo a la espera entonces del nuevo Release.

Muchas gracias por el soporte !

**Comment by damianwajser** [comment]
Solucionado en V1.2.1
